### ISSUE TITLE
"Additional Lists" loading very slowly for the first time

### ISSUE THREAD

**Issue by Atemu** [SEVENNetworks/AdClear#10]
Repro: Install the App and get to the "Additional Lists" screen. It should be blank.

cpuZ dump: http://valid.x86.fr/a/jjlwkn

**Comment by SEVENHelpdesk** [comment]
Hey, it's me from Reddit. I was wrong in thinking the fix was in the beta build right now, we will be putting it in the next build very soon.

**Comment by DustyWMorgan** [comment]
Hello Atemu, 

I apologize we seem to be appearing late on this issue. We have both an internal and external bug tracker so things sometimes appear to slip externally. We are working on this issue and thanks to your contribution we have narrowed down the cause. Please check back for more information if this is still occurring.

**Comment by james890526** [comment]
For my case, I updated to the latest beta 5.0.0.501194 and the additional lists never loads up even after waiting for more than 1 minute. I cleared data and cache, then only the additional lists came back.

**Comment by DustyWMorgan** [comment]
This issue seems to happen randomly between update intervals. We are looking into the cause of this bug. We may also need to add a resync button to minimize the effect of this issue.
