### ISSUE TITLE
AdClear VPN can't be started

### ISSUE THREAD

**Issue by ThomasCr** [SEVENNetworks/AdClear#108]
I can't use AdClear on my Samsung Tab S6 (SM-T860) with Android 10 / One UI 2.1.

After I switch the VPN on, the switch goes back to off state and get the message, that vpn could not activated because of a error. 

I have switchet vpn Logfile on in Advanced Settings and already reported it with the Feedback function.

**Comment by ThomasCr** [comment]
How to open the Logfile?

They are located in /storage/emulated/0/Android/data/com.seven.adclear/files/instabug/logs?

But can't be read?! Why is it not transparent for users?

**Comment by csandlin1** [comment]
Those are logs created by Instabug itself, not the VPN log or a logcat. 

Your report doesn't have the VPN log attached. Can you re-replicate with VPN log on and send in another bug report? We'll also try to replicate on our end. Apologies for the inconvenience.

**Comment by csandlin1** [comment]
Are you emulating the Samsung device?

**Comment by ThomasCr** [comment]
No, why should I emulate my tablet? I have again reported a bug. But I hope the Logfile is automatically attached, because I don't see an option to do so.

**Comment by ThomasCr** [comment]
Any update? Problem still exists.
