### ISSUE TITLE
Local DNS resolution blocked

### ISSUE THREAD

**Issue by ThomasCr** [SEVENNetworks/AdClear#111]
I can't open local dns hosts, when I use AdClear.

As example: http://webserver

Also when I add the local domain.

As example: http://webserver.fritz.box

Chrome gives me: DNS_PROBE_FINISHED_NXDOMAIN

I double checked if DNS filtering is switched off in AdClear.

Any Ideas?

**Comment by akomelj** [comment]
I have the exact same problem.
