### ISSUE TITLE
Ads Getting Through 

### ISSUE THREAD

**Issue by trennor** [SEVENNetworks/AdClear#12]
Downloaded any number of free apps,  all of them loaded with ads and not one of them blocked. OfficeSuite,  and MapMyRide are but two of them. Why?

**Comment by SEVENHelpdesk** [comment]
It's unfortunate that this is occurring. Could you provide us your device, OS, and AdClear version? You might be having issues with the VPN. What are some of the other apps this is happening in? We'll investigate them as well.

**Comment by OSMCanada** [comment]
In addition to above, ads are getting thru / showing up on cerain websites.  Currently ads are appearing on the KAT.CR domain website.

Technical Specs:
Dell Venue 10 5050 Tablet
Android 5.0.2
AdClear 5.50.1136.0

**Comment by DustyWMorgan** [comment]
@trennor build 501194 will fix the issue for the listed apps, let us know how it works for you.

@OSMCanada thanks for the comment, I will make this a separate issue and make sure we get right on this.
