### ISSUE TITLE
Ads not blocked by this two apps

### ISSUE THREAD

**Issue by Silverscape** [SEVENNetworks/AdClear#13]
Hi,

First, thanks for this great adblocker!

I noticed that ads from this two apps are still not blocked:

dreamEPG https://play.google.com/store/apps/details?id=de.cyberdream.dreamepg.free
dreamPlayer https://play.google.com/store/apps/details?id=de.cyberdream.dreamepg.player&hl=de

Would be nice, if you could block the annoying ads in these two apps.
Many Thanks in advance.

**Comment by DustyWMorgan** [comment]
Hello @Silverscape,

Can I ask what country you are located in? Google does not allow downloading either of your apps in USA and its not on apk mirror so I'll have to work around to take a look.

Also what build are you on? 501194 may already fix this issue.

Thanks

**Comment by Silverscape** [comment]
Hello,
thanks for the fast reply. I installed the latest beta version 501194 and you are right. The ads are gone.
This is great news! Also most ads from other apps disappeared with this version, but not all ads. Great improvement!
I will reopen a case when I find a new app with ads, if this is ok for you?

Also, will this beta version automatically update when a new version is released or do I have to check manually the XDA Forum or your website for updates?

Thank you very much.

**Comment by DustyWMorgan** [comment]
@Silverscape good to here! 

The update depends on if you are using the beta on GitHub or from our beta link, the one on GitHub will not update until after we release live, beta from our link will update on its own faster than the others.

If you need a link here it is: https://betas.to/st7txDFq
