### ISSUE TITLE
Ads visible on KAT.cr domain

### ISSUE THREAD

**Issue by DustyWMorgan** [SEVENNetworks/AdClear#14]
Copying comment from @OSMCanada found [here](https://github.com/SEVENNetworks/AdClear/issues/12#issuecomment-222376515)

> In addition to above, ads are getting thru / showing up on cerain websites. Currently ads are appearing on the KAT.CR domain website.
> Technical Specs:
> Dell Venue 10 5050 Tablet
> Android 5.0.2
> AdClear 5.50.1136.0

**Comment by SEVENHelpdesk** [comment]
This is either the biggest or second biggest torrent site. It will probably be malware redirects disguised as download buttons, etc. Should test the malware filter on it.

**Comment by OSMCanada** [comment]
I stopped using the KAT domain as I found another site which hosts zero ads and works well with AdClear (1337x.to)
