### ISSUE TITLE
"Additional List"  is extremely slow - didn't open for over a minute.  

### ISSUE THREAD

**Issue by Mbharath003** [SEVENNetworks/AdClear#16]
Additional lists from the menu is extremely slow to load the page but opens up quickly when we go through settings. 

Beta Build ending in 1244

**Comment by Mbharath003** [comment]
Correction -  additional lists from settings is slow too.

**Comment by SEVENNetworks** [comment]
This issue should not be occurring in the latest beta releases.  We recommend our users connect to a WiFi and refresh their Additional Lists before leaving the WiFi.  This will ensure that the Additional Lists are completely loaded to your device.

Please let us know if this does not work or if there is anything else we can help you with.  We are happy to look further into any issue you may have.

Thank you for using AdClear!
