### ISSUE TITLE
Clicking on Advanced Protection does nothing 

### ISSUE THREAD

**Issue by Mbharath003** [SEVENNetworks/AdClear#17]
Clicking on Advanced Protection from the menu does nothing.  Expect it to open the Advance Protection page? 

Beta Build ending in 1244

**Comment by SEVENNetworks** [comment]
We are sorry for the delayed response and this issue should be resolved in the latest releases.  Please let us know if it is still occurring and we will take a closer look into the issue.

Here is the link to follow to sign up for the latest beta release: https://betas.to/st7txDFq.

Thank you for using AdClear!
