### ISSUE TITLE
Sponsored Ads visible on Kijiji.ca domain

### ISSUE THREAD

**Issue by ghost** [SEVENNetworks/AdClear#19]
When I use the Opera Beta browser with its built-in adblocker, Opera is able to block the "Sponsored Links" on the Kijiji.ca website.

However when I only use Seven AdClear, the "Sponsored Links" ads appear. Appears on Chrome browser, not on Opera Beta browser as its built in adblocker does not show those sponsored links.  See screenshot below.

Specs:
ZTE K85 Tablet
Android 5.0.2
AdClear 5.50.1475.0

![img_20160704_154839](https://cloud.githubusercontent.com/assets/19637636/16568980/dfc1c638-41fe-11e6-84cf-0a9c779c9f5e.jpg)

**Comment by OSMCanada** [comment]
After recent AdClear update, seems as if the Sponsored Ads are now being blocked on the Kijiji.ca  domain. (screenshot below)

Specs:
ZTE K85 Tablet (non-rooted)
Android 5.0.2
AdClear 5.50.1544.0
Chrome 51.0.2704.81

**Comment by SEVENNetworks** [comment]
We are glad to hear the ads aren't showing now.  Please let us know if there is anything else we can help you with.  We apologize for the delayed response.

Thank you for using AdClear!
