### ISSUE TITLE
Additional Lists Blank Screen Fix

### ISSUE THREAD

**Issue by ghost** [SEVENNetworks/AdClear#21]
For those that have issues with getting a blank screen when selecting Additional Lists try the following troubleshooting steps:
1. Stop AdClear thru the app
2. Remove the Advanced Protection certificate (see app FAQ)
3. In Android Settings, Force Stop AdClear and clear both Cache and Data
4. Uninstall AdClear App
5. Power off your device
6. Boot device into Recovery Mode using power button and volume down buttons (web search this, works on non-rooted devices)
7. From the Recovery Mode menu, Wipe the Cache Partition only!!!
8. Once Cache Partition is wiped, reboot device
9. Re-download and Re-install AdClear
10. Additional List screen should work now

Tested and Verified above steps on:
ZTE K85 Tablet (non-rooted)
Android 5.0.2
AdClear 5.50.1544.0

**Comment by SEVENNetworks** [comment]
We recommend our users simply connect to a WiFi and then refresh the Additional Lists before leaving the WiFi.  This will ensure that the Lists are completely loaded to your device.  Please let us know if you are not able to get the Additional Lists after refreshing while connected to a WIFi.  We apologize for the delayed response.

Thanks for using AdClear!
