### ISSUE TITLE
additional lists not showing

### ISSUE THREAD

**Issue by rayman89** [SEVENNetworks/AdClear#23]
I'm on LG Leon android 5.0.1 and when I click on the additional list it just shows a blank screen.

**Comment by rayman89** [comment]
Reinstalling the app fixed it but idk why it happened.

**Comment by SEVENNetworks** [comment]
Sometimes the Additional List may not have completely loaded.  We recommend our users connect to a WiFi and refresh the Additional Lists before leaving the WiFi.  This will ensure that you have completely loaded the Lists to your device.  Please let us know if there is anything else we can help you with.
