### ISSUE TITLE
Snapchat doesn't work 

### ISSUE THREAD

**Issue by arvidholm** [SEVENNetworks/AdClear#24]
Snapchat doesn't work with the AdBlocker enabled on my Samsung galaxy s7

**Comment by csandlin1** [comment]
Hello. We've been investigating issues with Snapchat that arose during our latest few updates. The sign in process seems to fail and sending or receiving snaps either takes a long time or doesn't work at all. We hope to have this fixed within the next few updates.

**Comment by EnricoMartines** [comment]
Have You ensured You put Adclear as system admin? 
I had some issue with Pokémon GO, and After putting Adclear as system admin everything is working well

**Comment by arvidholm** [comment]
I had it as system admin, but it was fixed in the latest update :)

**Comment by EnricoMartines** [comment]
Happy it now works! Do You have any theyering issue?
Are You able to share your wifi using the hot spot wifi?
Thank You!

Il 19 ago 2016 4:49 PM, arvidholm <notifications@github.com> ha scritto:

I had it as system admin, but it was fixed in the latest update :)

-

**Comment by arvidholm** [comment]
I am not able to share my mobile data using the mobile hotspot feature

**Comment by EnricoMartines** [comment]
So this is a common issue... Thanks

Il 19 ago 2016 5:13 PM, arvidholm <notifications@github.com> ha scritto:

I am not able to share my mobile data using the mobile hotspot feature

-
