### ISSUE TITLE
Tethering wifi does not provide IP

### ISSUE THREAD

**Issue by EnricoMartines** [SEVENNetworks/AdClear#25]
On huawey Mate s, with or without wifi+, tethering the wifi to another device cause the device keep still "connecting".
The issue seems to be rekated to the IP address that is not provided back.
As workaround, I putted Adclear off, then connected the other device to my wifi, then switched on Adclear and the connection still work.

**Comment by SEVENNetworks** [comment]
AdClear will not work with WIFi tethering.  This is an Android rule that we don't have any control over.  Here is a link to follow about this matter: https://www.seven.com/adclear-faq.php#hotspot.  Please let us know if there is anything else we can help you with.
