### ISSUE TITLE
Invisible YouTube lists

### ISSUE THREAD

**Issue by DubLD** [SEVENNetworks/AdClear#26]
When I have it turned on and I can't see my watch lists on YouTube.

**Comment by ConnerJSP** [comment]
Same issue with me, a video will not be tagged "watched" when I watch it.

**Comment by csandlin1** [comment]
Are either of you in beta? We have a new update that addresses a few other YouTube problems that may also fix this.

**Comment by ConnerJSP** [comment]
I'm in beta, and have the most recent update (6.0.0.502148). I didn't see any fixes related to YouTube. However, the tagging is still unreliable; it sometimes works. And while addressing bugs, the app crashed when using Pandora, regardless of the fix for crashing. Do you automatically see a log for my app or do I have to report it when it happens?

~Kind regards, Conner Hill

**Comment by DubLD** [comment]
Not sure if I am, well, i'm definitely not currently I uninstalled it till a resolution was worked out. No sense in having something consume space and resources that ain't gonna be used till it is resolved. I had signed up for it though. Don't believe I was signed up long enough for a beta version to download before I uninstalled it.

-Don D. 




-------- Original Message --------

**Comment by ConnerJSP** [comment]
The bug with YouTube watch history is fixed. Thanks :) The recent fixes have helped a lot.

**Comment by DubLD** [comment]
Mine issue wasn't the history (if there's any difference) is was my que lists.

-Don D. 




-------- Original Message --------

**Comment by csandlin1** [comment]
Try clearing YouTube's cache in App Settings. You'll see better ad blocking from this as well.

**Comment by SEVENNetworks** [comment]
We now recommend our users clear the data for the YouTube app.  We have tested this method thoroughly and this is the most effective way to improve AdClear's ad blocking abilities.  Here is a link to follow that explains the updated steps: https://www.seven.com/adclear-faq.php#youtube_ads.

Also, we are aware that we may not be blocking all the ads in YouTube and are working to do so.  Please let us know if there is anything else we can help with.
