### ISSUE TITLE
Ping return OK also for machines down

### ISSUE THREAD

**Issue by raqua** [SEVENNetworks/AdClear#27]
When I ping some of my servers from my phone (using Tasker, but the same result is also using terminal), when machine is down, I still get response as if it was up. 
This is rather a big issue for me.

**Comment by SEVENNetworks** [comment]
Hello Raqua,

Thank you for downloading our app and providing your feedback.  We are sorry you are having issues.  Our app shouldn't affect pings.  Could you tell us more information about what you are experiencing?  Which ping are you trying?  Which kind of Tasker are you using?  This will help us better understand the issue you are experiencing.

Would you like to join the beta program?  You would receive the latest beta version weekly.  We believe you are a great candidate for the program.  If you are interested, please follow this link to sign up: https://betas.to/st7txDFq.

Please let us know how we can help you.  Thank you for your time and we hope you continue to use AdClear!

Chastity Rhodes
Data Specialist
SEVEN Networks, LLC

**Comment by SEVENNetworks** [comment]
Hello Raqua,

Could you tell us whether AdClear was turned off for Tasker on your phone?  You can check by accessing the top left-hand menu on the home page in AdClear.  Then go to Settings >Advanced Protection >Apps using network.  Please let us know if it was.

Thanks for your patience and time!

Chastity Rhodes
Data Specialist
SEVEN Networks, LLC

**Comment by raqua** [comment]
Hi, thanks for the reply.

Please ignore Tasker, this issue happens the same also on Android terminal, I think it is general networking thing, not Tasker specific. 

Please see the attached screenshots, that should make it clear. 
Note, machine named "amd" was down the whole time. 

![screenshot_20160831-231015](https://cloud.githubusercontent.com/assets/1541886/18146879/59a67d30-6fd2-11e6-89e4-2e924069fa26.png)
![screenshot_20160831-231044](https://cloud.githubusercontent.com/assets/1541886/18146880/59c26842-6fd2-11e6-8257-31b868d378fc.png)


I do not use advanced protection and in the "Apps using network" list is Tasker switch turned off as well as for the Terminal application.

**Comment by SEVENNetworks** [comment]
Thanks for replying and letting us know.  Please let us know if there is anything else we can help you with.

Thanks for using AdClear!
