### ISSUE TITLE
Application interference: tinyCamMonitor Pro

### ISSUE THREAD

**Issue by raqua** [SEVENNetworks/AdClear#29]
This is an app for streaming from IP cameras.

On device running Android 4.4, streaming works. 
On device running Android 6.0.1, streaming does not work and causes force close of your app. Strangely, VPN key is still present, I just get the error about app crash.

**Comment by csandlin1** [comment]
I believe we've gotten previous problems with this app before. Try whitelisting it under Advanced Protection > Apps Using Network. We apologize for the late response.
