### ISSUE TITLE
Certificate is not installing

### ISSUE THREAD

**Issue by SEVENHelpdesk** [SEVENNetworks/AdClear#3]
http://forum.xda-developers.com/showpost.php?p=65704791&postcount=93
http://forum.xda-developers.com/showpost.php?p=65705471&postcount=96
OnePlus One, Running Stock CM12.1.1-YOG7DAS2K1
I originally believed this was Cyanogenmod, which we can't test. Couldn't replicate at the time.

http://forum.xda-developers.com/showpost.php?p=65725511&postcount=115
http://forum.xda-developers.com/showpost.php?p=65726798&postcount=120
But this guy on a Note 5 and 5.1.1 is not prompted even though SSL says its on. His cert is empty.

http://forum.xda-developers.com/showpost.php?p=65727754&postcount=124
This guy commented a while back and seemingly had no issues until now.
He's got an S6 Edge running 5.1.1 as well.

**Comment by SEVENNetworks** [comment]
Fix has been made
