### ISSUE TITLE
adclear disabled for vpn error

### ISSUE THREAD

**Issue by usagetta** [SEVENNetworks/AdClear#31]
on my tablet chuwi v88  android 4.2.2 stock, adclear doesn't start , the red line under the red key says "adclear was disabled for vpn error". I installed the regula release and also the beta, but the result is always the same, is there a way to solve this issue? thanks

**Comment by csandlin1** [comment]
Try restarting your phone. That fixed the issue for a majority of users when it pops up.

**Comment by usagetta** [comment]
Thanks for the suggestion, unfortunately it doesn't work. Please give me
another solution

Il 30/set/2016 16:51, "csandlin1" <notifications@github.com> ha scritto:

**Comment by csandlin1** [comment]
Sorry for the late response. Have you tried updating ot the latest version?

**Comment by usagetta** [comment]
Thanks for your attention, the answer is yes, I am using the last release,
but the app still doesn't work. Is it possible to set the VPN manually?

Il 10/ott/2016 20:17, "csandlin1" <notifications@github.com> ha scritto:

**Comment by SEVENNetworks** [comment]
We are sorry for the delayed response.  Is this issue still occurring on your tablet?  AdClear is designed for phones but may still work on tablets.  Our VPN does have to be setup manually.  Here is a couple of links to follow with information on our VPN: https://www.seven.com/adclear-faq.php#vpn and https://www.seven.com/adclear-faq.php#vpn_installation.

Please let us know if there is anything else we can help you with.

Thank you for using AdClear!
