### ISSUE TITLE
Extreme battery usage

### ISSUE THREAD

**Issue by MLGPR0GAM3R** [SEVENNetworks/AdClear#33]
After charging the phone and leaving it running 24/7 it is consuming close 70% of my battery. Android 6.0.1, Samsung Galaxy S7

**Comment by csandlin1** [comment]
Is this based off of your Usage screen? The VPN function typically warps those numbers significantly. AdClear does have a negative effect on the battery, but it isn't like, say, your browser.

**Comment by MLGPR0GAM3R** [comment]
Yes if was based off usage screen. With it active it still drains the battery faster than wireless charging can charge.

**Comment by csandlin1** [comment]
Then those numbers aren't to be fully trusted. Would you like to join our beta program? We'd like to see what's going on. Just follow this link: [https://betas.to/st7txDFq](https://betas.to/st7txDFq) and send us a connection report after you try charging with the charger on.

**Comment by SEVENNetworks** [comment]
Hello Brian,

Thank you for downloading our app and providing your feedback.  We are sorry you are seeing a battery drain and are always working to improve the battery usage.  Here is a link that explains the battery usage: https://www.seven.com/adclear-faq.php#battery.

Please let us know if there is anything else we can help you with.  Thank you for your time and we hope you continue to use AdClear!

Chastity
Data Specialist
SEVEN Networks, LLC

**Comment by MLGPR0GAM3R** [comment]
Latest update fixed the issue. May have been a corrupt install first time around.
