### ISSUE TITLE
Several YouTube ads still showing

### ISSUE THREAD

**Issue by MLGPR0GAM3R** [SEVENNetworks/AdClear#35]
The ads that primarily seem to keep getting through are the wait 5 seconds and skip ads.

**Comment by csandlin1** [comment]
Hello. Have you tried clearing YouTube's cache?

**Comment by DustyWMorgan** [comment]
Hello, the steps above seem to have changed. Try the following and see how it works for you.

1. Enable AdClear and Advanced Protection (Certificate installed)
2. Force Stop the YouTube application
3. Clear Data of YouTube application
4. Open YouTube and begin playing videos ad free

If this does not work let us know.

**Comment by MLGPR0GAM3R** [comment]
The wait to skip ads still come through regardless of deleting data. It seems to happen when there is a change in connection (ie Wifi, 4G).
