### ISSUE TITLE
Slowing down the internet speed

### ISSUE THREAD

**Issue by jerryn70** [SEVENNetworks/AdClear#36]
I'm on the latest beta, the internet connectivity speed is too slow. apps are taking long time to load pages. When I disable the adclear protection internet speed comes back. 
I'm facing this issue in every apps. Even the apps that are on the whitelist also loads slowly.

**Comment by DustyWMorgan** [comment]
Hello I [messaged you on XDA](http://forum.xda-developers.com/showpost.php?p=69448752&postcount=975) and just wanted to follow up here as well. Please let me know any additional details you can provide.

**Comment by jerryn70** [comment]
Today I have tried the latest beta but this issue is still there.

**Comment by DustyWMorgan** [comment]
Hello @jerryn70,

Could you send feedback or report a connection issue in app while using the beta? This will help us get more information for your specific issue. We still are unable to replicate your issue ourselves and the information may help with this.

Thanks for letting us know your issue is still occurring, we will work to get it resolved.

**Comment by jerryn70** [comment]
@DustyWMorgan 

Connection issue has been sent. And I don't know whether you guys received it or not. 
According to my finding the slow down occurring most of the time when I'm using internet through wifi . 
Yesterday I browser internet through mobile data (4G VoLTE) and never noticed slow down. 

But while using wifi with adclear protection I'm facing slow down, when I disable adclear then speed will increase to normal .

**Comment by DustyWMorgan** [comment]
@jerryn70 we located your report and are looking into the issue and will update you on anything we find. We may notify you by app if anything else is required so please do not uninstall or clear app data if possible. If you do need to do either, just let us know and we can contact you some other way.

Thanks for helping us improve the app.

**Comment by jerryn70** [comment]
@DustyWMorgan

I have mailed screen recording videos and some other info to feedback@seven.com hope that will help more to understand the issue

**Comment by DustyWMorgan** [comment]
@jerryn70 thanks we have received this, this helps a lot. We think we have found your issue. We are working on the fix and should get a build to you soon. I will let you know as soon as possible.

**Comment by jerryn70** [comment]
@DustywMorgan

Can I update to the latest beta that released now (8/12/16 9:59pm) ? Or should I stick with the older version till this issue solve

**Comment by DustyWMorgan** [comment]
@jerryn70 yes please update this new release should contain the fix for this issue. Please let us know how it works for you.

**Comment by jerryn70** [comment]
@DustywMorgan

Issue is not fixed on this update.

**Comment by jerryn70** [comment]
Hello @DustywMorgan ,


I have tried uninstall / reinstall but there is no change. What should I do ? I can't continue with this app because of slow connection.
 If you need connection report or anything contact me today itself, because tomorrow I'm going to uninstall this app, hope you understand my situation.

**Comment by DustyWMorgan** [comment]
@jerryn70 please try to replicate the issue and send a connection report in app right after. This will ensure we get the logging we need. If you could allow some time on wifi to ensure the logs send as well this will help ensure all the information gets to us.

No problem, we understand. We hope you will keep the beta app to download again when a fix is out.

**Comment by jerryn70** [comment]
@DustywMorgan

Connection report has been sent.
Sure I will test the next beta.
