### ISSUE TITLE
AdClear is creating a pin code without user entering one

### ISSUE THREAD

**Issue by SEVENHelpdesk** [SEVENNetworks/AdClear#4]
LG v10 on Verizon
From XDA:
http://forum.xda-developers.com/showpost.php?p=65711704&postcount=105
http://forum.xda-developers.com/showpost.php?p=65721409&postcount=108
User tried to enter in the code ten times, and his phone factory reset and wiped out his SD card. Lead programmer says the code would have been "7777" if the user had no choice in the matter.

**Comment by SEVENNetworks** [comment]
Fix has been made
