### ISSUE TITLE
additional Filters are not displayed 

### ISSUE THREAD

**Issue by cusn** [SEVENNetworks/AdClear#41]
When install AdClear, additional Filters are often not displayed, white screen. Refresh countless times may be displayed. It's been a couple of hours today, and it's not showing up yet.
All versions are the same, v502687 is not the same situation.

**Comment by SEVENNetworks** [comment]
Are you connected to a WiFi when you are trying to refresh the Additional Lists?  We recommend our users connect to a WiFi and staying connected until the the refreshing process is complete.  If you are connected to a WiFi while refreshing, please let us know and we will take a closer look into the issue.  Please let us know if there is anything else we can help you with.

Thank you for using AdClear!

**Comment by cusn** [comment]
Indeed connected to the wifi, and has remained connected.

**Comment by SEVENNetworks** [comment]
Thank you for responding.  We are going to need to open an investigation for your issue, so we can resolve it properly.  Would you mind joining our beta program?  Our beta version has enhanced features, which helps us isolate and pinpoint the cause of the problem quickly.  Plus, the beta version may resolve your issue without having to go through the investigation process.

Here is the link to follow to join our beta program: https://betas.to/st7txDFq.  Please consider joining.  This is the best way to get to the bottom your issue.  Please let us know if there is anything else we can help you with.

Thank you for using AdClear!

**Comment by cusn** [comment]
Thx, I still do not participate in the test.

**Comment by SEVENNetworks** [comment]
We understand if you don't want to join the beta program.  The beta version is the same as the general release version of AdClear except for the enhanced features it has.  Also, the beta version usually includes fixes for different bugs the general release versions have.  So the beta version is not a test but a more advanced version.

As always, please let us know if there is anything else we can help you with.

Thank you for your time and we hope you continue to use AdClear!

**Comment by cusn** [comment]
Others are very good, thx.
