### ISSUE TITLE
Not functioning: "AdClear has lost permission to use the VPN"

### ISSUE THREAD

**Issue by fraxen** [SEVENNetworks/AdClear#42]
Hi Adclear,

I really like your app, and I have installed it on several of my devices, and most of the time it works well!

Now, my primary phone - a Sony Xperia Z5Compact, it works sometimes... I recently did an uninstall/install, and then it started working fine, but it has now stopped working again.

After reboot of my phone I get the notification "AdClear has lost permission to use the vpn" - I open the app and it says enabled, and I can't see any setting that I can change anything. After that it says:
"SEVEN AdClear Disabled. AdClear has been disabled. Touch to open app"
I open the app - it says 0 blocked today and "Protection enabled" [latter in green] on the top. I can toggle the protection label with the button.
I have the key in the notification bar and "Network may be monitored" notification - so things are like they should, right? But when I now open an app with google play ads (which I know AdClear should block when it works), like LocalCast, then there are plenty of ads, and it still lists 0 blocked in AdClear.

Phone is running Android 6.0.1 and I am on local Wifi (but I get the same results on data/4g). AdClear just updated itself to 6.0.0.502921

I don't see any way to re-enable the permission to use the VPN...

**Comment by csandlin1** [comment]
Are you using background data restriction or power saving mode?

**Comment by fraxen** [comment]
Nope, and nope (for the latter, it gets enabled when the battery gets below a threshold, when I tested it was off).

Now I did an experiment (again) - uninstalled and reinstalled the app, went through the tutorial, added the additional Swedish filter and enabled advanced protection. Made sure that protection is enabled. Then tested in an app that I know has ads - it doesn't show any. Back to AdClear, it lists "1 Blocked Today". Excellent! I restarted, and I got the notification that it had lost permission. I re-enabled AdClear and tested, and it still works. I hope it lasts!

**Comment by csandlin1** [comment]
That's good news! This must mean the notification is just malfunctioning. Keep us posted!

**Comment by fraxen** [comment]
It keeps stopping to work, with no indication - it says in the app that it is enabled...

**Comment by csandlin1** [comment]
Would you be willing to join our beta program so that we can see what's going on?

**Comment by fraxen** [comment]
Sure

**Comment by csandlin1** [comment]
Follow this link to join! 

https://betas.to/st7txDFq
