### ISSUE TITLE
list of sites showing ads

### ISSUE THREAD

**Issue by jerryn70** [SEVENNetworks/AdClear#43]
List of sites showing ads 

http://onelike.tv/

Waptricks.sextgem.com

https://www.kambimalayalamkathakal.com

Pronhub.com

Xvideos.com

Xnxx.com 

m.spankbang.com

Redtube.com

http://m.99danji.com/news/107782/

http://www.playground.ru/

Gismeteo.ru 

http://m.ltaaa.com/ 

http://www.5zdm.com/play/17200/1/1.html

m.gutenberg.org

m.toysrus.com

http://www.quankan.tv/

http://m.ybdu.com/xiaoshuo/4/4398/557103.html

https://news.yandex.ru/Moscow

**Comment by DustyWMorgan** [comment]
A lot of these websites will need our certificate to be able to block effectively. Please install and enable Advanced Protection under Menu -> Settings -> Advanced Protection.

Any ads using https will not be detected without Advanced Protection.

**Comment by jerryn70** [comment]
@DustyWMorgan
I'm already in advance protection

**Comment by DustyWMorgan** [comment]
It seems from your logs and screen you sent us Advanced Protection may not be on/working. Can you verify that on the main screen you do not see text like "Block YouTube ads? Click here."? If you do and press that it will take you to enable Advanced Protection.

We will continue to look into this issue as well for any that slip past Advanced Protection. Thanks

**Comment by jerryn70** [comment]
@DustyWMorgan

Maybe that log is sent before activating advance protection. That log is sent for the issue #36.

After fixing the issue #36 i will look more into issue.
