### ISSUE TITLE
Not blocking Pop-up& & Vibrating Ads

### ISSUE THREAD

**Issue by jerryn70** [SEVENNetworks/AdClear#44]
Pop-up and vibrating ads are shown. Is there any way to block pop up ads and vibrating ads? I mean when i try to download files from some sites my phone starts vibrating and a pop up will come like saying your phone is in danger or phn got virus scan now/install antivirus or maybe install this app to remove virus from your phone, click here to download games and movies etc like pop up and vibrations.

●Adclear version : latest beta
●Operating system : Android Marshmallow 6.0.1

●Below i listed some of that kind of sites●

https://dropapk.com/munh0ciu8h89

http://ul.to/9mfxlw6x

https://dailyuploads.net/ifsksrv94c1r

https://filescdn.com/fwy5vrgsysq7

https://uplod.ws/ny5w868j53k7

https://userscloud.com/7ww5ltgaf6kt

http://hugefiles.net/4o2sy9b5gxnx

**Comment by DustyWMorgan** [comment]
This is an interesting case and may be something we should add to our malware filter. We should block these kinds of ads. Make sure you have enabled Advanced Protection when browsing.

We will look into this issue and let you know what we find.

**Comment by jerryn70** [comment]
@DustyWMorgan

I'm already using advance protection. Still getting pop-up and vibrating ads

**Comment by euzada** [comment]
@jerryn70 I found a solution for your problem. With the help of the amazing work of Adclear you can use brave browser (chrome with AdBlock) and  activate "block script" and "fingerprinting protection" on your page by clicking on the logo of brave when you open a page. I tried all your link and it's working fine. Good luck. 
I hope Adclear team will find how brave do the blocking and integrate the solution in the future version.

**Comment by jerryn70** [comment]
@euzada cash you make it more clear
Is it adclear or brave browser blocking that ads ?

**Comment by csandlin1** [comment]
@euzada Yes, could you clarify what what these features in brave are stopping as compared to AdClear?

**Comment by jerryn70** [comment]
@csandlin1

● Fully HTTPS connection

● Block ads & tracking

● Block Scripts

● Block 3rd party cookies

● Block pop up

These are the most top features of brave. 
The "block scripts" feature stops redirecting and "block pop-up" feature stops pop-up.
This 2 feature helps to solve this issue #44

**Comment by csandlin1** [comment]
The malware filter should already handle those redirects. We may need to look into more third party support if that's not the case. We should have more help coming with our redesign. :) Let us know how that goes when it's out.
