### ISSUE TITLE
Nexus 6 is not receiving update files

### ISSUE THREAD

**Issue by SEVENHelpdesk** [SEVENNetworks/AdClear#5]
Nexus 6 with Marshmallow

User got an update notification, but clicking it did nothing. Tried reinstalling AdClear, but it wouldn't install. Rebooted, and it installed along with the update (I believe), but the update we pushed yesterday brings the same problem.
Asked user to go to his downloads to see if he could manually install it from there, but no file existed besides the original download.

More info needed to see if this affects other phones.

**Comment by DustyWMorgan** [comment]
We have not seen this issue again. Must have been an anomaly. If we see this issue again lets reopen this ticket.
