### ISSUE TITLE
QooApp doesn't show the list of games when filtered

### ISSUE THREAD

**Issue by Zero3K** [SEVENNetworks/AdClear#51]
When I try to view the list of games that QooApp is offering for download while its filtered, I get a continuous looping circle instead of the list.

**Comment by csandlin1** [comment]
It sounds like the app is timing out. Are you running any other network applications alongside AdClear?

**Comment by Zero3K** [comment]
I am not running any other network applications alongside it.

**Comment by csandlin1** [comment]
I would try reinstalling the app and certificate as it sounds like something went wrong during installing. Timeouts are usually situational and can be fixed with normal troubleshooting such as that, rebooting, etc.

**Comment by Zero3K** [comment]
Have you tried it out yourself?

**Comment by csandlin1** [comment]
Yes, we've been unable to replicate on our end. Sending us logs through the Help and Feedback section will help us see what's going on. Be sure to mention your Netflix issue as well, as it seems like they're related.

**Comment by Zero3K** [comment]
I chatted with the support team regarding Netflix. They are going to add it to the bypass list. Maybe the same should be done to QooApp.
