### ISSUE TITLE
v503934 automatically exit 

### ISSUE THREAD

**Issue by cusn** [SEVENNetworks/AdClear#52]
when set up the seventh step，v503934 automatically exit.

**Comment by csandlin1** [comment]
Do you mean this is happening in the tutorial?

**Comment by cusn** [comment]
Yes，after "Manage apps"

**Comment by csandlin1** [comment]
Have you tried the Skip button?

**Comment by cusn** [comment]
Yes,it works.
But the tutorial is normal before v503934 such as v503857,
Can you fix the v503934?

**Comment by csandlin1** [comment]
Can you send us a connection report through Help and Feedback? We'd like to investigate what's causing this.

**Comment by cusn** [comment]
I don't know how to do.

**Comment by csandlin1** [comment]
The option is located under Help and Feedback in the menu.

**Comment by csandlin1** [comment]
I apologize, I meant the Report Connection Issue should be under User Input in the menu.

**Comment by cusn** [comment]
In"Help & Feedback" ,only some Description about how to use adclear.

"Send feedback " : 
"Talk to us"
"Report a problem"
"suggest an improvement"
It is the same in writing here.

**Comment by cusn** [comment]
after clicking "Report Connection Issue",switch to "Report a problem"

**Comment by cusn** [comment]
I click that blue arrow,It says, have recevied the feedback.

**Comment by csandlin1** [comment]
Hm, it shouldn't be switching like that, but I believe we got it. You use a Xiaomi phone?

**Comment by cusn** [comment]
Yes

**Comment by csandlin1** [comment]
We'll investigate what happened and get back to you ASAP.

**Comment by cusn** [comment]
OK,thank you.
