### ISSUE TITLE
Ads not blocked in Tumblr app

### ISSUE THREAD

**Issue by matoro** [SEVENNetworks/AdClear#54]
It would seem that Adclear is unable to catch ads in the Tumblr app. Be aware that I have yet to come across an adblocker which can do so on a nonrooted device. Willing to provide debug logs or anything but I cannot do logcats as I'm on a non-rooted Nougat Galaxy S7.

**Comment by csandlin1** [comment]
Hello. Thanks for letting us know. In the app, can you send us a connection report (menu option) perhaps with a screenshot of the ad?

**Comment by matoro** [comment]
@csandlin1 Thanks for the quick response.  I've sent a log and 2 screenshots with the reply email throwaway19587@gmail.com (forwards to my real email).  Let me know if there is any other information I can supply.  I have been unable to block these ads with DNS66 (blocks at DNS level) or Adhell (blocks using KNOX), so if you can manage to squash these without root you'll have my respect.

**Comment by csandlin1** [comment]
Sure thing! Tumblr's ads can be pesky, but we're always working on improving. You should be seeing at least some of them blocked.

**Comment by matoro** [comment]
@csandlin1 I received an update via the in-app bug tracker explaining the cause of the issue.  It looks like this Nougat change is at fault: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

So there seems to be no way to get an unrooted device on Android 7 to trust user-installed certificates if the app is targeting API level 24 or later.  However, if I am interpreting the post correctly, I believe it will accept certificates signed by the system-level CAs?  The Adclear certificate is self-signed, but out of curiosity, would this be possible if the certificate were to be signed by one of the system CAs such as Startcom, Comodo, Digicert, etc?

Many thanks for your great work.

**Comment by csandlin1** [comment]
I apologize about no mentioning the Nougat change. I should've thought of that before suggesting you contact the team.t 

We wouldn't be able to get added on Android normally due to their "security" settings as mentioned in their blog, which essentially means they're taking the discretion to decide by themselves. I don't believe our certificate would meet the criteria to get signed under that. I'm not aware of apps that are working with this functionality.

We're the first nonroot app to block encrypted ads, and it's a major focus for us to find a way around Google. We're investigating ways around it.

**Comment by matoro** [comment]
That's great, I'm glad progress is being made on circumventing these nonsensical and anti-user restrictions.  Would Let's Encrypt possibly help with this somewhat?  According to their blog post https://letsencrypt.org/2016/08/05/le-root-to-be-trusted-by-mozilla.html as of 2016 August their root certificate is in the Mozilla trusted CAs, although looking at the Android system CAs on my phone I don't see them in there.  However they are a major CA and the fact that they are already trusted by Mozilla is a fairly strong argument for requesting their inclusion in Nougat.  I have used LE for sites before and the process for generating signed certificates is incredibly painless, they are a fantastic service.

**Comment by csandlin1** [comment]
Like they say, they need to make a major partnership and effort for that to happen. We'd rather focus our resources on improving the app and finding a way to circumvent it.

With the Tumblr ads, we just won't be able to block right now.

**Comment by matoro** [comment]
I see.  I just updated the app MX Player to find that it has also adopted the same strategy and now cannot be blocked.  It would seem we're currently losing this one, and since there's no known workaround without root at the moment, I'll close this.  However I will see about getting in touch with the Let's Encrypt team and see if they have made any communication with Google about being added to the list of Android system CAs, and if I find any information on breaking this particular issue I will mention it here.  Thanks for your continuing great work on this app.
