### ISSUE TITLE
App fails to open from Notification

### ISSUE THREAD

**Issue by JeremyWW** [SEVENNetworks/AdClear#55]
Actually only happens occasionally. I'll touch the notification and on the Adclear 'panel' that appears with Session/Duration/Sent/Received, I'll touch 'Configure'. Most of the time that will open the app, but occasionally I get a small error panel in grey at the bottom of the screen that says Adclear isn't available (sorry, can't remember the exact words until it happens again). I'm using your latest release (just checked) on a Galaxy S7 running Android 7.0. Thanks.

**Comment by csandlin1** [comment]
This is something we'd like to take a look at and patch up. Can you send us a log through the app menu?

**Comment by JeremyWW** [comment]
I've just enabled the Debug Log. Is that all I need to do for the moment?

**Comment by csandlin1** [comment]
Once you see it happen again, send a report through the menu and it will send us what exactly happened.

**Comment by JeremyWW** [comment]
Will do...

**Comment by JeremyWW** [comment]
I'm sorry. I don't understand which menu option to use to send you a report.

**Comment by JeremyWW** [comment]
OK. The message I'm seeing is 'Unavailable(Always_on VPN)'
Don't know which option to use to send you that report though. If I disable/enable Adclear it clears the problem and I can then open Adclear from the notification panel.

**Comment by JeremyWW** [comment]
I did actually manage to send you a report, I think. Did you get it? Been checking this occasionally and it seems to happen following a change such as coming off WiFi onto mobile data and vica versa, or making some change in Adclear Settings.

**Comment by csandlin1** [comment]
Yes we did. Sorry, we just made changes to our report system and I had given you the old instructions.
