### ISSUE TITLE
[Feature request] Additional filter: hungarian websites

### ISSUE THREAD

**Issue by akoslaczko** [SEVENNetworks/AdClear#56]

**Comment by akoslaczko** [comment]
It would be very nice to have a filter option for Hungarian websites as well. Thanks in advance!

**Comment by csandlin1** [comment]
We can easily get that added for you! If you would send this through Send Feedback or Chat > Suggest an Improvement it'll make a ticket for our programmers to see. The list should update very quickly afterwards.

**Comment by akoslaczko** [comment]
Thanks, for the quick reply, sounds awesome. Did send the request using the above method as well.
