### ISSUE TITLE
opening links slow when https filtering is enabled

### ISSUE THREAD

**Issue by godey4me** [SEVENNetworks/AdClear#57]
Hi, 
Just started using adclear a few days ago. When https is enabled, and a link is clicked it stalls for a bit before making any progress to open. Sometimes it does not open at all. It seems to happen a lot when the phone has laid idle for a couple of minutes. when disabled links work but I get some adds filtering through.  
I am on galaxy note 8, Android version 8.0.
Thanks

**Comment by csandlin1** [comment]
The next time this occurs, could you send us a bug report under Settings > Help & Feedback > Report a Problem > Connection Issue. It can be difficult to determine when AdClear is the cause of these problems, so we like to take a look when we can.

**Comment by godey4me** [comment]
I did send a bug report through the app's settings.
I tinkered around a bit and found that it wasn't https filtering that was causing the issue. A rookie mistake of turning too many knubs when I started using adclear. Renamed the post title to reflect the change

With dns request blocking off, some ads filter through apps like terrarium . When dns request blocking is on all apps are blocked but i get intermittent network issues described earlier in the OP and online radio drops connections. I have experienced this on web pages, tunein radio and bbc iplayer radio.

Thanks for awesome app. The best i can come to use, dns66, blokada etc cannot match.

**Comment by csandlin1** [comment]
This seems related to a bug we've been investigating. We're about to release a new beta tomorrow and could use your help, if you wouldn't mind. It would help us tons to run a few tests. We'd get it fixed ASAP, as it's a high priority issue for us.

**Comment by godey4me** [comment]
Great! I will be on the lookout for the BETA.

**Comment by csandlin1** [comment]
I'll let you know when it's out! Thank you so much.

**Comment by csandlin1** [comment]
https://betas.to/oDBC6Xy4

Here's the link for the beta. If you can send us a bug report once you see your problem arise, let us know you're godey from github. We'll get started on investigating right away.
