### ISSUE TITLE
In app updates slow and unreliable

### ISSUE THREAD

**Issue by sashaman** [SEVENNetworks/AdClear#59]
As the title says - most of the time inapp updates either take forever or i end up downloading updates from the Website... 
How can i supply debug or log files? 
Thanks in advance

**Comment by csandlin1** [comment]
Hey sashaman, thank you for contacting us. Part of the slowness comes from our own hardware. Our server can just be a little bit slow sometimes, but it shouldn't be unbearable in length. If you go to Help & Feedback in AdClear, it will allow you to Report a Problem. Pick connection issue (any are fine though), and be sure to mention you're from GitHub in the report. That'll send us the log file. 

We have another report of this occurring with the latest version, so we very much appreciate you doing this! We'll see if we can fix it.
