### ISSUE TITLE
AdClear breaks automatic backup to Samsung Cloud

### ISSUE THREAD

**Issue by DustyWMorgan** [SEVENNetworks/AdClear#65]
The user has configured automatic backup every 24 hours when the battery is charging, WiFi is on, and the screen is off. However, backups always fail when AdClear is enabled. We need to check if AdClear is blocking something here.

**Environment:**
 - Device: samsung SM-G950N
 - OS: 26
 - AdClear version: 9.5.4.538-ga

**Additional context**
More info here: https://dashboard.instabug.com/applications/adclearforandroid/beta/bugs/13008

**Comment by bdefriend-seven** [comment]
The problem should be fixed in this build:
[adclear_9.6.0.585-beta.apk.zip](https://github.com/SEVENNetworks/AdClear/files/3184369/adclear_9.6.0.585-beta.apk.zip)

**Comment by SophiaGlazova** [comment]
Fixed in !190 and released in 9.7.0
