### ISSUE TITLE
[9.6.0] Reports of high battery drain 

### ISSUE THREAD

**Issue by csandlin1** [SEVENNetworks/AdClear#67]
With the latest release, we have gotten multiple reports of battery drain (including from those aware of battery monitor & VPN interactions) which are showing a legitimate spike in CPU usage. We need to investigate ASAP.

**Comment by DustyWMorgan** [comment]
We believe we have fixed the battery drain issues and will be releasing a beta client with the fix shortly. Let us know if you still experience the battery drain issues and send us a battery report in-app under Settings > More > Generate battery report.
