### ISSUE TITLE
Android KitKat fails to parse APK data

### ISSUE THREAD

**Issue by twse** [SEVENNetworks/AdClear#75]
**Steps to reproduce:**
1. Download the APK for AdClear under KitKat.
2. Open the APK file to install it.

**Expected results**
Installing the app should work.

**Actual results**
Package has error on parsing.

**Comment by csandlin1** [comment]
We no longer support Android versions below 5.1. You can still use the last APK with KitKat support here:  https://github.com/SEVENNetworks/AdClear/releases/tag/v9.4.0.462-ga 

You will still continue to get easylist updates on this APK.
