### ISSUE TITLE
App setup stuck at terms and conditions.

### ISSUE THREAD

**Issue by vushe** [SEVENNetworks/AdClear#77]
**Describe the bug**
Setup stuck at terms and conditions. Nothing shown in setup window except button, which I can't push because I immediately redirected to system's browser and page https://adclear.com/en/terms/

**To Reproduce**
1. Start installing apk
2. Click start
3. Enjoy

OnePlus 6t with Android 9 (OxygenOs 9.0.15), latest update. Apk downloaded today from official site, have no idea about version.

**Comment by DustinMorgan** [comment]
Thanks for letting us know. We believe we have fixed this in our 9.8.0 beta release over at issue #76. 

We released this fix to all users this morning, let us know if the issue still occurs on that build.

**Comment by vushe** [comment]
Awesome, it works now. Thanks and apologies for duplicate!
