### ISSUE TITLE
[BUG] Ad blocking settings revert to default after restarting phone

### ISSUE THREAD

**Issue by csandlin1** [SEVENNetworks/AdClear#78]
**Describe the bug**
User reports that upon rebooting, ad blocking is turned back on for apps that AdClear detects ads in. I have successfully replicated.

**To Reproduce**
1. Turn ad blocking on/off for an app that detects ads (whatever the opposite is)
2. Reboot phone (Restart VPN option doesn't matter)
3. Check Manage Apps

**Expected behavior**
User settings remain the same.

**Environment (please complete the following information):**
Huawei Nexus 6P
Android 8.1
GA

**Comment by Bigmike69** [comment]
Same issue as well. Google Pixel 2 XL on Android 9.0

**Comment by DustinMorgan** [comment]
Fixed in !245
