### ISSUE TITLE
Battery Life issues

### ISSUE THREAD

**Issue by SEVENHelpdesk** [SEVENNetworks/AdClear#8]
We are getting several notices of AdClear draining more battery than it should be. This isn't tied to the inflated numbers on the Battery screen; in general, people are seeing a notable decrease in battery life throughout their day.

**Comment by DustyWMorgan** [comment]
We have found the rate of our ad blocker to be low from research, generally less than 6% for most users for a full day use. The inflated number has been from apps receiving their data minus the ads through our app. Closing.
