### ISSUE TITLE
I want to confirm a place

### ISSUE THREAD

**Issue by ghost** [SEVENNetworks/AdClear#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1.Does AdClear's private DNS and the filtering rules in it share the same list of lists?
http://www.seven-china.com/AdClear_DNS_CN/adclear-dns-overview.html
2.Excuse me, I found out that the advertisement server was not blocked. Where is the feedback appropriate? APP or Email?

**Additional context**

**Comment by DustinMorgan** [comment]
Let us know what platform you are using and any issues found at feedback@seven.com.
