### ISSUE TITLE
[BUG] 9.10.2.753-ga installs but doesn't work on Essential PH1 phone

### ISSUE THREAD

**Issue by legolego** [SEVENNetworks/AdClear#84]
I was able to install and run this version on my phone The previous version would just crash as soon as it was launched, as the release notes say, but this version doesn't actually block any ads on my phone. The pulldown notification on the phone only says: Today Blocked - Ad: 0
Ads are visible on all apps/pages. I'm at 66% (Medium Setup), I don't have Dubbel installed, but Ad blocking and HTTPS filtering have green checkmarks next to them. I have the key icon (vpn) in the top right. AdClear doesn't crash or complain about anything, it's just not working. 

**Environment (please complete the following information):**
 - Device: Essential PH1
 - OS: Android 10
 - AdClear version 9.10.2.753-ga

**Comment by DustinMorgan** [comment]
Thanks for the report, we were able to reproduce the same issue internally as well and are working on a fix.

**Comment by DustinMorgan** [comment]
This issue should now be fixed in our 9.11.0 release for all Android 10 devices.
