### ISSUE TITLE
Update AdClear More Often

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#85]
Can you please update AdClear more often because apps often get updated and then AdClear stops working, it doesn’t block ads in apps and a lot of apps still have connection issues with AdClear enabled, and also the support often doesn’t respond to in app feedback and bug reports

**Comment by DustinMorgan** [comment]
Hey, thanks for the question.

AdClear is a little bit different from a lot of apps, we designed it in a way that we can update its core functionality (blocking ads) from our server without requiring an update to the app. We do this through filterlists which should sync to your device within 12 hours of an update on our server. The rules in the lists can fix connection issues and block ads in apps or websites that we were unable to at the original time of release.

We try to cover everything, however, there are a lot of apps and websites so we may miss some of the apps or websites important to you. If that occurs feel free to open an issue here in GitHub or send in feedback in-app.

I apologize if some of your feedback has not received a response. I believe we received a similar email from you so I will check the issues related to that address and see if anything was missed by our support team. If you still do not receive a response feel free to email me directly at the email in my profile.

**Comment by GKid94** [comment]
@DustinMorgan Ok but can you then add a GitHub link in the app so that people can open issues here, and also add the filter lists in the app and the option to manually check for filter list updates

**Comment by DustinMorgan** [comment]
@GKid94 we could do something like that. What did you have in mind? Just a link to our issues page so you can make the issues with a mobile browser?

We do have the filter lists visible in the app. You can find those in Settings > Ad Blocking > Additional filters. They update automatically but you can also swipe down on the list to update them manually as well.

**Comment by GKid94** [comment]
1) Yes
2) Ok can you add an option to update those filters manually

**Comment by DustinMorgan** [comment]
The option should already be included but hidden. Go to **Settings > Ad Blocking > Additional filters** and drag down on the list of filters. You should see an icon indicating the filters are refreshing.

**Comment by GKid94** [comment]
Well it's better to add the option to press it to update the filter lists because a lot of people wouldn't know how to update them

**Comment by DustinMorgan** [comment]
That is probably true for a lot of users. We will take that into consideration when adding #64 and redesigning the filter UI.

**Comment by GKid94** [comment]
And maybe also add a filter list update widget to add it on the home screen so that you can quickly minimize the app that is showing ads and update the filter lists and then continue to use the app
