### ISSUE TITLE
AdClear Crashes

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#87]
AdClear crashes often

![Screenshot_2019-11-17-07-37-33](https://user-images.githubusercontent.com/18757054/69004060-5136eb80-090d-11ea-88dd-03f6e86713b3.png)

**Comment by DustinMorgan** [comment]
@GKid94 what was occurring at the time of the crash? Were you on any specific screen or did the app crash while in the background?

**Comment by GKid94** [comment]
It crashes randomly even when I'm not using the phone

**Comment by DustinMorgan** [comment]
@GKid94, unfortunately, our automatic crash detection is not very helpful for this crash and we aren't able to reproduce on a similar device. Can you use our beta and the next time you observe the crash send in-app feedback mentioning GitHub 87 (this issue)?

**Comment by GKid94** [comment]
I've sent the report
