### ISSUE TITLE
Can not view previously submitted feedback

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#88]
The chat support history option is often missing

![2019-11-17 07 52 44](https://user-images.githubusercontent.com/18757054/69004201-7fb5c600-090f-11ea-8b9b-712857098254.png)

**Comment by DustinMorgan** [comment]
Thanks for letting us know. It looks like Instabug (our feedback provider) may have removed this on their side. We will add our own option to view past feedback if that is the case.

**Comment by GKid94** [comment]
Ok thx

**Comment by SophiaGlazova** [comment]
This issue should now be fixed on 9.12.0 release.
