### ISSUE TITLE
[Google Play] Apps updates not downloading

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#89]
The apps on the Play Store won't install or update, they just get stuck on the "Downloading" message

![Screenshot_2019-11-19-21-24-49](https://user-images.githubusercontent.com/18757054/69183777-e86d9000-0b13-11ea-8ec5-e1d536e16ee3.png)

**Comment by DustinMorgan** [comment]
@GKid94 we have had a few reports of this but we are not able to replicate the issue on our devices.

Would you be able to do the following?

Using AdClear beta (can be downloaded on [GitHub here](https://github.com/SEVENNetworks/AdClear/releases/tag/v9.11.0.760-beta)):

1. Enable the VPN
2. Navigate to **Settings > Advanced -> VPN Log Capture** and enable the setting
3. Attempt to download from Google Play for a few minutes
4. Click on our notification that shows "AdClear might be running slowly"
5. Turn off the VPN Log Capture setting
6. You will be shown an in-app report. Submit the report mentioning GitHub 89 (this issue)

This will give us additional logs and hopefully will capture the issue.

**Comment by GKid94** [comment]
I've sent the report

**Comment by DustinMorgan** [comment]
Thanks for sending that in. When you check **Settings > Manage apps** do you have "Download Manager" enabled for ad blocking? You may need to select the "Show system apps" option in the overflow menu (three vertical dots in the upper right screen).

If you have it enabled, does disabling it allows downloads to go through?

**Comment by GKid94** [comment]
Yes it's enabled and I still have the issue when I disable the ad blocking for download manager

![Screenshot_2019-11-19-23-20-57](https://user-images.githubusercontent.com/18757054/69191931-d09e0800-0b23-11ea-92d2-1993007908d8.png)

**Comment by GKid94** [comment]
This is with ad block disabled fo download manager, it still won't download

![Screenshot_2019-11-19-23-39-59](https://user-images.githubusercontent.com/18757054/69193009-24115580-0b26-11ea-8833-2a87a6395867.png)

**Comment by GKid94** [comment]
I've sent the report, maybe you can add an option to download the report so that users can also send it here on GitHub
