### ISSUE TITLE
Apps not blocked

### ISSUE THREAD

**Issue by Steve2Go** [SEVENNetworks/AdClear#9]
Hi guys, 2 apps that the ads are getting past:
TrackID by Sony
MX Player - main screen and when video is paused.

Hope you can work something out :)

**Comment by SEVENHelpdesk** [comment]
Thanks for the heads up. I've been able to see ads in both as well.

I've been testing TrackID and have only found ads after it identifies the track. Where else have you seen them?

**Comment by Steve2Go** [comment]
That's the only spot for me also.

Kind regards,
Steve

**Comment by Steve2Go** [comment]
The ads do look similar between apps - possible connection perhaps?

Kind regards,
Steve

**Comment by SEVENHelpdesk** [comment]
It seems that they're both using google's network. We have someone looking into both apps right now.

**Comment by SEVENHelpdesk** [comment]
We have a fix. It's got to be tested and validated first, though. We'll let you know when it's up!
