### ISSUE TITLE
[YouTube] Not blocking yellow ad indicators

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#94]
Block the yellow ad blocks on the YouTube video bar

![Screenshot_2019-11-23-03-23-13](https://user-images.githubusercontent.com/18757054/69484497-406a0680-0e34-11ea-9d62-abc862059197.png)

**Comment by DustinMorgan** [comment]
Just to confirm the actual ads are blocked on YouTube even when these indicators are shown?

We may be able to create a filter to remove the indicators as well.

**Comment by GKid94** [comment]
Yes the ads are blocked but those yellow blocks are still shown
