### ISSUE TITLE
[Gameloft] Website Connection Issues

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#97]
This website has connection issues when AdClear is enabled https://support.gameloft.com/login

**Comment by csandlin1** [comment]
I've been unable to replicate any connection issues. Can you be more specific about what's happening? The site does appear to be massive, so it's giving me slowness with or without AdClear on.

**Comment by GKid94** [comment]
The website won't load pages and content often when AdClear is enabled
