### ISSUE TITLE
[Steam] App Connection Issues

### ISSUE THREAD

**Issue by GKid94** [SEVENNetworks/AdClear#99]
The Steam app won't load pages when AdClear is enabled https://play.google.com/store/apps/details?id=com.valvesoftware.android.steam.community

**Comment by csandlin1** [comment]
I'm able to load pages. Is this a consistent issue? We might just go ahead and bypass Steam for being a store. @DustinMorgan

**Comment by GKid94** [comment]
The app works now, maybe it was something with Steam
